# Generated by Django 6.0.5 on 2026-05-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='medico.demo', max_length=150, unique=True)),
                ('password_hash', models.CharField(default='password_seguro', max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_colegiatura', models.CharField(max_length=50, unique=True)),
                ('universidad', models.CharField(default='USIL', max_length=255)),
                ('especialidad', models.CharField(choices=[('Psicología Clínica', 'Psicología Clínica'), ('Neuropsicología', 'Neuropsicología Aplicada'), ('Terapia Conductual', 'Terapia Cognitivo-Conductual'), ('Salud Preventiva Ocupacional', 'Salud Preventiva Ocupacional')], default='Psicología Clínica', max_length=100)),
                ('pais', models.CharField(default='Perú', max_length=100)),
                ('idiomas', models.CharField(default='Español / Inglés Avanzado', max_length=100)),
                ('publico_objetivo', models.CharField(choices=[('BAJO', 'Carga Mental Baja'), ('MODERADO', 'Carga Mental Moderada'), ('CRITICO', 'Carga Mental Crítica')], default='MODERADO', max_length=20)),
                ('descripcion_trayectoria', models.TextField(blank=True, null=True)),
                ('distorsiones_tratadas', models.JSONField(default=list)),
                ('telefono', models.CharField(max_length=20)),
                ('enlace_agenda', models.URLField(blank=True, default='https://wa.me/51986575756', max_length=500)),
                ('avatar_icono', models.CharField(default='👨\u200d⚕️', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(default='Giancarlo Huisa', max_length=150)),
                ('puntuacion_total', models.IntegerField()),
                ('distorsion_predominante', models.CharField(max_length=100)),
                ('nivel_carga_calculado', models.CharField(default='MODERADO', max_length=20)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
