# Generated by Django 6.0.5 on 2026-05-21 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_especialista_fecha_registro_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaEspecialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_nombre', models.CharField(max_length=150)),
                ('alumno_correo', models.EmailField(max_length=254)),
                ('motivo', models.TextField(default='Derivación por estrés académico.')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDO', 'Atendido')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='api.especialista')),
            ],
        ),
    ]
