# Generated by Django 6.0.5 on 2026-05-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_consultaespecialista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='avatar_icono',
            field=models.TextField(blank=True, default='https://cdn-icons-png.flaticon.com/512/3135/3135715.png', null=True),
        ),
    ]
