# Generated by Django 6.0.5 on 2026-05-21 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_especialista_avatar_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('codigo_identificacion', models.CharField(max_length=50, unique=True)),
                ('carrera', models.CharField(choices=[('Escolar', 'Educación Secundaria / Escolar'), ('Ingeniería de Sistemas', 'Ingeniería de Sistemas e Informática'), ('Psicología', 'Psicología'), ('Administración', 'Administración de Empresas'), ('Derecho', 'Derecho')], default='Escolar', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_nivel_carga', models.CharField(default='SIN_TEST', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='consultaespecialista',
            name='alumno_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_solicitadas', to='api.alumnousuario'),
        ),
        migrations.AddField(
            model_name='historialtest',
            name='alumno_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_tests', to='api.alumnousuario'),
        ),
    ]
