# Generated by Django 6.0.5 on 2026-05-25 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alumnousuario_consultaespecialista_alumno_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.TextField()),
                ('enunciado', models.TextField()),
                ('orden', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProfesional', models.TextField()),
                ('apellidoProfesional', models.TextField()),
                ('telefonoProfesional', models.TextField()),
                ('correoProfesional', models.TextField()),
                ('clave', models.TextField()),
                ('especialidad', models.TextField()),
                ('validacion', models.IntegerField(default=0)),
                ('universidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.TextField()),
                ('apellidoUsuario', models.TextField()),
                ('telefonoUsuario', models.TextField()),
                ('correoUsuario', models.TextField()),
                ('clave', models.TextField()),
                ('nivel_riesgo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='consultaespecialista',
            name='alumno_usuario',
        ),
        migrations.RemoveField(
            model_name='consultaespecialista',
            name='especialista',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='especialista',
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('valor_puntos', models.IntegerField(default=0)),
                ('idEscenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='api.escenario')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField(default='Pendiente')),
                ('fecha', models.DateTimeField()),
                ('idProfesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesional')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='HistorialTest',
        ),
        migrations.DeleteModel(
            name='AlumnoUsuario',
        ),
        migrations.DeleteModel(
            name='ConsultaEspecialista',
        ),
        migrations.DeleteModel(
            name='Especialista',
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
