# Generated by Django 6.0.5 on 2026-05-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_escenario_profesional_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='avatar_icono',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='descripcion_trayectoria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='enlace_agenda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
