# Generated by Django 6.0.5 on 2026-05-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profesional_avatar_icono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='generoProfesional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='generoUsuario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
