# Generated by Django 6.0.5 on 2026-05-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profesional_generoprofesional_usuario_generousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='motivo',
            field=models.TextField(default='Sin motivo especificado'),
        ),
    ]
