# Generated by Django 6.0.3 on 2026-05-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_reserva_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='contacto_correo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='contacto_whatsapp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
